Create testing
FAA-VAIL-Project/openGCAS pull request #14
Opened 2022-08-19 18:20 UTC by quothbonney

Created a basic testing structure. Note the new directory `dependencies/` which links some relevant deps for testing. The main change is the new directory `testing/` which contains a `CMakeLists.txt` as well as individual tests.

By far the most complex test was ensuring that the PolySelect will never fail and never create intersecting polygons.

2022-08-19 18:21 UTC, quothbonney reviewed
Need to get merged ASAP

2022-08-20 04:09 UTC, c-bik requested changes
Docker breaks on this PR. Needs to fixed and ideally tests should be run in docker as well.

2022-08-20 04:09 UTC, c-bik commented on tests/raster_test.cpp
> +}
Remove empty lines
Add a new line at EOF

2022-08-20 04:09 UTC, c-bik commented on tests/main.cpp
> +#include <catch2/catch.hpp>
New line at EOF

2022-08-20 04:09 UTC, c-bik commented on tests/CMakeLists.txt
> +
Remove empty line

2022-08-20 04:09 UTC, c-bik commented on tests/raster_test.cpp
> +    const char *ga = "../../data/gabon.tif";
Use parameters for test files instead of hardcoding.

2022-08-20 04:09 UTC, c-bik commented on tests/raster_test.cpp
> +            std::cout << p2.x << " " << p2.y << "   " << q2.x << " " << q2.y << "\n\n\n";*/
Remove commented code

2022-08-20 04:09 UTC, c-bik commented on src/main.cpp
>  #include "../include/Raster.h"
Unused include?

2022-08-20 04:09 UTC, c-bik commented on CMakeLists.txt
>  target_link_libraries(openGCAS PRIVATE GDAL::GDAL)
New line at EOF

2022-08-22 02:03 UTC, quothbonney commented on tests/raster_test.cpp
> +    const char *ga = "../../data/gabon.tif";
Unsure of what you meant by this. Fixed the rest.

2022-08-22 06:56 UTC, c-bik commented on tests/raster_test.cpp
> +    const char *ga = "../../data/gabon.tif";
I was hoping there is a way to specify data for testing externally. I need to read about CMake tests to see if it's possible. All good for now.

2022-08-22 06:56 UTC, c-bik approved these changes

2022-08-22 06:57 UTC, merged